### ISSUE TITLE
Support a direct database insertion option for fast visit generation

### ISSUE THREAD

**Issue by bx80** [piwik/plugin-VisitorGenerator#138]
### Objective

Enhance the visitor generator so it can also be used to quickly create large datasets for performance testing.

### The Problem

Currently the visitor generator creates visits by sending tracker API requests. This is great for testing API functionality and closely simulates a real visit, but has the downside of being very slow when trying to generate a large number of visits.

For example, generating 1,000 fake visits for 1 day takes, 2min30sec or 7 requests per second.
So generating 100,000,000 visits at this rate would take ~4,000hrs or almost six months.

### Some Background

As part of previous load testing work [this](https://github.com/matomo-org/matomo/tree/tracker-db-load-tester) standalone load testing script was created and can insert fake visits directly into a database at a rate of up to 3,000 visits per second.

Given adequate server resources this should be capable of generating a 100,000,000 visit dataset in just over 10hrs.

However this script was only intended for short term internal use and therefore lacks the quality of fake data provided by the visitor generator and doesn't have the ease of use required for general availability.

### Proposed Solution

Add the direct data insertion functionality from the load testing script into the Visitor Generator plugin as an alternative option to sending requests via the tracking API.

- Including this functionality in the visitor generator plugin makes it available to anyone wanting to test large datasets.
- The existing high-quality fake data generation code can be reused for direct database inserts.
- The Console command interface means it can be used to automatically generate datasets to a required size in CI pipelines.
- Normal usage of the visitor generator plugin is unaffected.

This option would only generate fake visits, not visits loaded from logs.

### Command Syntax and Examples
```
./console visitorgenerator:generate-visits-db
    --idsite=1                          Site for which to generate the visits
    
    --days=xx                           Create visits for this many days into the past
    --dates=yyyy-mm-dd,yyyy-mm-dd       OR create visits between these dates
    
    --total-visits=yy               Create this many total visits across all chosen days
    --daily-variance                    Percent variance in daily visits for total-visits
    
    --daily-visits                      OR number of visits to create each day, either an exact
                                        number or a random range
```

Create visits for a specific year, there will randomly be between 2466 - 3014 visits per day and a total of exactly 1 million visits.
```
./console visitorgenerator:generate-visits-db --idsite=1 --dates=2023-01-01,2023-12-31 --total-visits=1000000 --daily-variance=10
```

Create visits 90 days into the past from the current date with each day having somewhere between 200 and 600 visits, there will be somewhere between 18,000 and 54,000 total visits
```
./console visitorgenerator:generate-visits-db --idsite=1 --days=90 --daily-visits=200,600
```

Create visits for the previous 7 days with 1,000 visits per day, 7,000 visits total.
```
./console visitorgenerator:generate-visits-db --idsite=1 --days=7 --total-visits=7000
```

**Comment by michalkleiner** [comment]
I like the idea of going straight into the database, though could there be aspects or behaviour of the tracker and/or subsequent processing that the direct-to-db approach would circumvent? Things such as data anonymisation or device detection or anything that acts on the data received through the tracker endpoint?

**Comment by bx80** [comment]
Yes, absolutely, it couldn't be used for testing any of the features provided by tracker request processors but that's not the intended use anyway. Things like device detection can be handled as part of log record insertion if necessary, so we can parse the user agent using device detector methods and then insert the results into the correct log table fields, if that proves too costly for performance then we can simply randomize the values from in memory arrays. Data anonymisation probably isn't an issue as all the generated data will be fake anyway. 

The aim would be to get the resulting database inserted visits as near to those generated via a tracking request as we can, using the visitor generator plugin's random data with as little additional processing/fakery as possible.

**Comment by caddoo** [comment]
Makes sense to me, the only thing to think about maybe, is that if you are inserting things directly into the database, skipping the application, is there risks that this tool falls behind and becomes incompatible with a possible schema change.

Or are the tables this will be writing into at a low chance of change?
