### ISSUE TITLE
Fix broken link from User Interface --to-->    Readme

### ISSUE THREAD

**Issue by atom-box** [piwik/plugin-VisitorGenerator#145]
Broken link

![image](https://github.com/matomo-org/plugin-VisitorGenerator/assets/22874146/2cf7c9cc-fa98-474e-82bf-50ba1f407284)

As shown in the screenshot, if you go to Matomo >> Development >> Visitor Generator >> [README] it is a broken link.

Please edit so it reaches the following URL 
https://github.com/matomo-org/plugin-VisitorGenerator

**Comment by AltamashShaikh** [comment]
@matomo-org/core-team Is `https://developer.matomo.org/guides/reproducing-issues#testing-data` the correct URL ?

**Comment by sgiehl** [comment]
I guess it actually refers to the plugins README.md file. So basically https://plugins.matomo.org/VisitorGenerator
