### ISSUE TITLE
Error when i generate visits

### ISSUE THREAD

**Issue by Germen38** [piwik/plugin-VisitorGenerator#15]
When i type this in the console ./console visitorgenerator:generate-visits --idsite 2. 
I get this error 

 [Zend_Db_Adapter_Exception]
  SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.

  [PDOException]
  SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.

**Comment by mattab** [comment]
Hi  @Germen38 
Looks like your MySQL refuses connection. Not a Piwik issue as such
