### ISSUE TITLE
hey, i think you are expert in piwik, do you know how to develop a new login plugin with openid?

### ISSUE THREAD

**Issue by wei1215583760** [piwik/plugin-VisitorGenerator#18]
i will be grateful if you give me some advice, thank you!

**Comment by sgiehl** [comment]
Have a look at our developer guide: https://developer.piwik.org/develop
And maybe have a look at the existing login plugins:
https://github.com/piwik/plugin-LoginLdap
https://github.com/uniwue-rz/LoginShibboleth
https://github.com/sgiehl/piwik-plugin-GoogleAuthenticator
