### ISSUE TITLE
Can't find the UI

### ISSUE THREAD

**Issue by wanjizheng** [piwik/plugin-VisitorGenerator#19]
"The plugin adds a new item to the Piwik admin UI visible only for users having Super User access under the section "Development". There you can select a site and for how many days in the past you want to generate new visits."

I am the Super User, but there isn't a section called "Development" and I couldn't find this UI in the admin panel (I'm using PIWIK 3.1.0).  Please let me know where is the UI!

**Comment by mneudert** [comment]
Have you activated the development mode for your instance?

You can do that by running `./console development:enable` from a shell in your piwik folder. If successful the section you are searching for appears at the bottom of the admin menu. If you navigation to "Diagnostics > Config file" there should be a variable "enabled" in the section "Development" displaying your current state.

_(I think the description should be expanded to include the development mode requirement...)_

**Comment by wanjizheng** [comment]
Thanks mneudert, super helpful.

**Comment by mattab** [comment]
Added a note in the README in https://github.com/piwik/plugin-VisitorGenerator/commit/4018a591cb07de3a70709a8b9dfed7908e945f77
