### ISSUE TITLE
Add Option to provide a different Piwik(tracker)-URL, e.g. if Piwik is behind a loadbalancer

### ISSUE THREAD

**Issue by peterbo** [piwik/plugin-VisitorGenerator#4]

**Comment by mnapoli** [comment]
There is a `--piwik-domain` option by default on all console commands, I wonder if this is what you mean? @mattab?

**Comment by peterbo** [comment]
Hi @mnapoli no, that's not quite it. Have a quick look at the commit. I think you will know immediately, what this aims to do. Perhaps this is not the perfect name for the parameter. Do you have other suggestions?

**Comment by peterbo** [comment]
Hi @mattab, can this be merged?

Thanks!

**Comment by mattab** [comment]
Hi @peterbo thanks for making the changes, looks good (I haven't tested it but I trust you did!)
