### ISSUE TITLE
Tracking failure when using plugin in Matomo 4.1.1

### ISSUE THREAD

**Issue by Starker3** [piwik/plugin-VisitorGenerator#66]
When using the Visitor Generator plugin in Matomo 4.1.1 the following tracking error occurs:

Measurable | Problem | Solution | Date | Page URL | Tracking URL | Action
-- | -- | -- | -- | -- | -- | --

Hilpert, Flatley and Bashirian (Id 2) | Request was not authenticated but authentication was required. | Set or correct a "token_auth" in your tracking request. Learn more | Feb 22, 2021 00:26:24 | http://example.org/?utm_campaign=bsa&utm_term=buildinternet | action_name=ExampleCode+-+technology+with+passion&idsite=2&rec=1&r=299079&h=7&m=17&s=55&url=http%3A%...

![image](https://user-images.githubusercontent.com/20905821/108645506-f3ce1900-7517-11eb-815e-61e74714e6b8.png)

No errors are returned when running the console command to generate the visit data
![image](https://user-images.githubusercontent.com/20905821/108645737-aef6b200-7518-11eb-9de3-5afd761fe660.png)

No data is generated for the reports in Matomo 
![image](https://user-images.githubusercontent.com/20905821/108645793-d8afd900-7518-11eb-8e10-b748a1e26a69.png)

Using the latest 4.0.3 plugin version.

**Comment by sgiehl** [comment]
I'm actually not able to reproduce that with lastet 4.x-dev. For me the command works locally

**Comment by Starker3** [comment]
I tested again on 4.2.1 with plugin version 4.0.3 and still get the same error. 
The console command works, but it results in a tracking failure with no tracking data recorded.

**Comment by sgiehl** [comment]
@Starker3 is it a fresh install? 
Normally the tracking urls should contain a valid system token_auth that automatically requested for the tracking requests.
Can you see if the tracking urls contain any token_auth or is it missing or empty?

**Comment by Starker3** [comment]
@sgiehl It's not a fresh install of Matomo, but it is a fresh install of the plugin (Updated this Matomo install from 3.14.1)

This is the tracking URL shown in the tracking failures:

```idsite=2&rec=1&apiv=1&rand=1636495582&_id=e4002ba0f2c2dd70&fla=1&java=1&qt=0&realp=0&pdf=0&wma=0&ag=0&h=12&m=34&s=6&res=1024x768&cookie=1&_cvar=%7B%225%22%3A%5B%22VisitorType%22%2C%22NewLoggedOut%22%5D%7D&cvar=%7B%223%22%3A%5B%22_pks%22%2C%22SKU2%22%5D%2C%224%22%3A%5B%22_pkn%22%2C%22PRODUCT+name%22%5D%2C%225%22%3A%5B%22_pkc%22%2C%22Electronics+%26+Cameras%22%5D%7D&url=http%3A%2F%2Fexample.org%2Findex.htm&urlref=http%3A%2F%2Fpiwik.org%2Fcontribute%25&action_name=incredible+title%21&cdt=2021-03-16+04%3A18%3A38&cip=13.5.111.3&token_auth=__TOKEN_AUTH__&dp=1```

I haven't checked the matomo.php access log to see if the token auth shows there, would the tracking failure show the token_auth in the failed tracking URL?

**Comment by Starker3** [comment]
Forgot to add, it's the same error as previously: 

Request was not authenticated but authentication was required. | Set or correct a "token_auth" in your tracking request. Learn more
-- | --

**Comment by sgiehl** [comment]
@Starker3 could you check if there is an app specific token added for the superuser? There should be one created for creating the visits...

**Comment by Starker3** [comment]
@sgiehl ~~No token was created for the visitor generator plugin. The only token is the one created by the Matomo 4 migration.~~
Correction, there is an app specific token for "visit generator" but it shows as never used

**Comment by sgiehl** [comment]
I think we disabled or limitted updating the usage while tracking.
@Starker3 could you share the system info data? I'm currently not able to reproduce it...
Is anyone else able to reproduce the issue locally?

**Comment by Starker3** [comment]
Actually, I think that Auth token was one I generated while trying to figure out why it wasn't working. I uninstalled the plugin completely, deleted all the auth tokens and reinstalled, ran the command again and have the same error as previously. 
No auth token was generated when reinstalling or running the command again.

System report attached
[matomo_system_check_17-March.txt](https://github.com/matomo-org/plugin-VisitorGenerator/files/6151962/matomo_system_check_17-March.txt)

**Comment by Starker3** [comment]
I tried again on an install that only ever had 4.x installed and having the same error (The plugin was not installed previously)
No auth token was generated, tracking failed because of no auth token in the requests.

**Comment by diosmosis** [comment]
@Starker3 an idea if you haven't tried already: enable tracker debug logging, enable logging to file, then run the visitorgenerator and check the logs. (It may take some tweaking to actually get the logging to file to work, at least it's taken a bit for me sometimes.) There should be some more information there.

**Comment by tsteur** [comment]
fyi see https://developer.matomo.org/api-reference/tracking-api#debugging-the-tracker

**Comment by Starker3** [comment]
I enabled tracker debugging and when checking the log file I realised that this issue is related to `login_whitelist_ip[]`
After removing the login_whitelist_ip from the config file the visitor generator was able to succeed without issues.

Should we perhaps have a check to warn for this when using this command? Additionally, which IP would need to be added to the whitelist to allow the plugin to work? (I'm guessing it's the public IP of the server the plugin is running on)

**Comment by Starker3** [comment]
FYI adding the server IP (Public IP or local) doesn't seem to work for the visitor generator plugin.

**Comment by sgiehl** [comment]
@Starker3 when setting an `login_allowlist_ip` I'm able to reproduce. 
@tsteur Is it expected that authenticated tracking requests should be checked with the allow list?

**Comment by tsteur** [comment]
It says in the config

> Note that neither this setting, nor the "login_allowlist_apply_to_reporting_api_requests" restricts authenticated tracking requests (tracking requests with a "token_auth" URL parameter).

**Comment by sgiehl** [comment]
@tsteur so it would be a bug in core if authenticated tracking requests would fail due to login_allowlist_ip restrictions?

**Comment by tsteur** [comment]
By the sounds yes 👍
