### ISSUE TITLE
Generates visits only today

### ISSUE THREAD

**Issue by geekdenz** [piwik/plugin-VisitorGenerator#78]
`./console visitorgenerator:generate-visits --start-date=2007-12-20 --idsite 1 --days 1`

creates visits only on the day the command is run.

See https://github.com/matomo-org/matomo-php-tracker/blob/a7809441e5909d331c19338c718f8800a4cad5e5/MatomoTracker.php#L1817-L1907 and debug there using above command.

It may be a configuration issue but I could not find out what it might be. Maybe it is a regression as found with the team.

**Comment by tsteur** [comment]
@geekdenz I tested using `console visitorgenerator:generate-visits --start-date=2020-12-20 --idsite 1 --days 1 ` and it works fine for me. Can you maybe check that this works? 2007 is probably too far back (before Matomo was created).

**Comment by geekdenz** [comment]
Yes, you are right.

Tried `./console visitorgenerator:generate-visits --start-date=2015-12-20 --idsite 1` and it was fine.

Thanks for trying it out!

**Comment by tsteur** [comment]
Reason this didn't work was because a log data retention of 5000 days was configured. Any tracking request older than 5000 days would then throw an exception / error because there is no point in tracking that data that would be deleted right away.

**Comment by geekdenz** [comment]
Thanks for your explanation, @tsteur .

For future reference:

You can find the option under Administration - Privacy - Anonymize data - Regularly delete old raw data - Delete logs older than (days).
