### ISSUE TITLE
Update the doc: Enabling development mode breaks deployed install

### ISSUE THREAD

**Issue by heurteph-ei** [piwik/plugin-VisitorGenerator#92]
From: https://forum.matomo.org/t/enabling-development-mode-breaks-deployed-install/44444

***Appartently you do not need to enable dev mode to use the plugin. Instructions in the plugin itself should be amended, since the ones in the website are correctly not mentioning the dev mode.***

For tracing purposes: the post:
>Just installed 4.6.2 in a plain U20.04 VM, no issues until I tried to enable development mode throut CLI in order to use the VisitorGenerator Plugin.
>
>Enabling the development mode returns error in dashboard visualization as per attached and makes left side menu unresponsive when entering the settings menu.
> ![Dashboard in error](https://forum.matomo.org/uploads/db1181/original/2X/9/90d3a6eebc2c8f3910cb95d0f2101207238db211.png)
>
> HTTP requests log:
> ![HTTP requests log](https://forum.matomo.org/uploads/db1181/original/2X/b/bcec8549c8baabd0a34df761b279c402676de2a7.png)
>
>**Appartently you do not need to enable dev mode to use the plugin. Instructions in the plugin itself should be amended, since the ones in the website are correctly not mentioning the dev mode.**

**Comment by sgiehl** [comment]
@heurteph-ei 
Thanks for creating the issue. It is required to enabled the development mode in order to get the menu item in the UI. The console command should also work without development mode.

**Comment by tsteur** [comment]
![image](https://user-images.githubusercontent.com/273120/150410173-f5e58fda-2553-4f85-86f2-140e3a8353fe.png)


@heurteph-ei was there maybe an Ad Blocker active or something similar?

FYI it mentions that Development Mode is enabled but it can be missed quite easily 
![image](https://user-images.githubusercontent.com/273120/150410350-e59ca351-0789-4cbb-ac73-87a2f9e5bce4.png)

**Comment by heurteph-ei** [comment]
@tsteur I don't know, I just pasted the forum post here as the user said something was missing in the documentation...
He just said that he wanted to use the VisitorGenerator Plugin. So he read the doc that said to enable the Development mode. With this mode enabled, the Matomo UI crashes. With this mode disabled, it doesn't crash.
I will ask the user if he has some browser plugin installed or not...

**Comment by sgiehl** [comment]
In that case it might be more relevant to check why the Matomo UI crashes when development mode is enabled. If that is the case I guess we either should fix that it works in a normal build. Or disable it so no one can crash Matomo with it.

**Comment by heurteph-ei** [comment]
Waiting for the user reply... ;-)

**Comment by AltamashShaikh** [comment]
@heurteph-ei any update ?

**Comment by AltamashShaikh** [comment]
Closing this issue due to no response from the user.
